import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "secure vault",
  description: "Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
